#!/bin/bash
set -euo pipefail

mkdir -p "__AKTINUPDATEDIR__"

apt update
apt install aktin-notaufnahme-dwh >"__AKTINUPDATEDIR__/log" 2>&1

if [ $! -eq 0 ]; then
	SUCCESS="true"
else
	SUCCESS="false"
fi

cat <<EOF >"__AKTINUPDATEDIR__/result"
{
	"success": $SUCCESS,
	"time": "$(date)"
}
EOF

